-- MySQL Schema for CRM Database
-- Converted from PostgreSQL for MySQL compatibility

-- Table: users (Must be created first due to foreign key references)
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('Super Admin', 'Telecaller', 'Counsellor', 'Manager', 'Sales Representative') NOT NULL DEFAULT 'Telecaller',
    phone VARCHAR(20),
    department VARCHAR(100),
    status ENUM('active', 'inactive') DEFAULT 'active',
    permissions JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_users_email (email),
    INDEX idx_users_role (role),
    INDEX idx_users_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: leads
CREATE TABLE leads (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    city VARCHAR(100),
    neet VARCHAR(10),
    course VARCHAR(100) DEFAULT 'MBBS',
    destination VARCHAR(100),
    remark TEXT,
    notes TEXT,
    source VARCHAR(100),
    status VARCHAR(50) DEFAULT 'New',
    assigned_to INT,
    assigned_to_name VARCHAR(255) DEFAULT 'Unassigned',
    assigned_date TIMESTAMP NULL,
    last_call_date TIMESTAMP NULL,
    next_followup_date TIMESTAMP NULL,
    is_transferred BOOLEAN DEFAULT FALSE,
    transferred_date TIMESTAMP NULL,
    transferred_to INT,
    transferred_to_name VARCHAR(255),
    imported_date VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    follow_up_status ENUM('pending', 'missed') DEFAULT 'pending',
    reopen_requested BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (transferred_to) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_leads_phone (phone),
    INDEX idx_leads_status (status),
    INDEX idx_leads_assigned_to (assigned_to),
    INDEX idx_leads_next_followup (next_followup_date),
    INDEX idx_leads_is_transferred (is_transferred),
    INDEX idx_leads_transferred_to (transferred_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: call_history
CREATE TABLE call_history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lead_id INT NOT NULL,
    caller_id INT NOT NULL,
    caller_name VARCHAR(255) NOT NULL,
    call_date TIMESTAMP NOT NULL,
    call_remark TEXT NOT NULL,
    call_outcome VARCHAR(50) NOT NULL,
    call_reason VARCHAR(100),
    next_followup_date TIMESTAMP NULL,
    duration VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_ip VARCHAR(45),
    user_agent TEXT,
    FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
    FOREIGN KEY (caller_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_call_history_lead_id (lead_id),
    INDEX idx_call_history_caller_id (caller_id),
    INDEX idx_call_history_call_date (call_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: audit_logs
CREATE TABLE audit_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    user_name VARCHAR(255),
    action ENUM('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT') NOT NULL,
    entity_type ENUM('Lead', 'User', 'CallHistory', 'Auth', 'Setting') NOT NULL,
    entity_id INT,
    details TEXT,
    ip_address VARCHAR(45),
    user_agent TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_audit_logs_user_id (user_id),
    INDEX idx_audit_logs_action (action),
    INDEX idx_audit_logs_entity_type (entity_type),
    INDEX idx_audit_logs_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: notifications
CREATE TABLE notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    type ENUM('new_lead', 'assignment', 'status_change', 'call_log', 'lead_converted') NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    lead_id INT,
    lead_name VARCHAR(255),
    unread BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
    INDEX idx_notifications_user_id (user_id),
    INDEX idx_notifications_unread (unread),
    INDEX idx_notifications_created_at (created_at),
    INDEX idx_notifications_type (type),
    INDEX idx_notifications_lead_id (lead_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: company_settings
CREATE TABLE company_settings (
    id INT PRIMARY KEY,
    companyName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    address TEXT,
    website VARCHAR(255),
    timezone VARCHAR(100) DEFAULT 'Asia/Kolkata',
    currency VARCHAR(10) DEFAULT 'INR',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: user_settings
CREATE TABLE user_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    displayName VARCHAR(255),
    email VARCHAR(255),
    language VARCHAR(50) DEFAULT 'English',
    dateFormat VARCHAR(50) DEFAULT 'DD/MM/YYYY',
    timeFormat VARCHAR(10) DEFAULT '24h',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: telecaller_daily_stats
CREATE TABLE telecaller_daily_stats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    telecaller_id INT NOT NULL,
    date DATE NOT NULL,
    total_calls INT DEFAULT 0,
    contacted_count INT DEFAULT 0,
    interested_count INT DEFAULT 0,
    negative_outcome_count INT DEFAULT 0,
    wrong_number_count INT DEFAULT 0,
    not_reachable_count INT DEFAULT 0,
    followups_missed INT DEFAULT 0,
    negative_outcome_ratio DECIMAL(5,2) DEFAULT 0.00,
    interested_ratio DECIMAL(5,2) DEFAULT 0.00,
    abuse_flag BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (telecaller_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE KEY unique_telecaller_date (telecaller_id, date),
    INDEX idx_telecaller_stats_date (date),
    INDEX idx_telecaller_stats_abuse (abuse_flag),
    INDEX idx_telecaller_stats_telecaller (telecaller_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: student_applications
CREATE TABLE student_applications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    mobile VARCHAR(20) NOT NULL,
    whatsapp VARCHAR(20),
    email VARCHAR(255) NOT NULL,
    gender ENUM('Male', 'Female', 'Other') NOT NULL,
    nationality VARCHAR(100) NOT NULL,
    aadhar VARCHAR(12) NOT NULL,
    passport_status ENUM('Available', 'Applied', 'Yet to Apply', 'Have Passport', 'Don''t Have Passport') NOT NULL,
    passport_number VARCHAR(50),
    passport_issuance_date DATE,
    passport_expiry_date DATE,
    file_number VARCHAR(100),
    father_title ENUM('Mr.', 'Mrs.', 'Ms.', 'Dr.', 'Prof.') DEFAULT 'Mr.',
    father_name VARCHAR(100) NOT NULL,
    father_mobile VARCHAR(20) NOT NULL,
    father_occupation VARCHAR(100) NOT NULL,
    mother_title ENUM('Mr.', 'Mrs.', 'Ms.', 'Dr.', 'Prof.') DEFAULT 'Mrs.',
    mother_name VARCHAR(100) NOT NULL,
    mother_mobile VARCHAR(20),
    mother_occupation VARCHAR(100),
    address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    pincode VARCHAR(10) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    school_10_name VARCHAR(255) NOT NULL,
    board_10 VARCHAR(100) NOT NULL,
    percentage_10 DECIMAL(5,2) NOT NULL,
    year_10 VARCHAR(4) NOT NULL,
    school_12_name VARCHAR(255) NOT NULL,
    board_12 VARCHAR(100) NOT NULL,
    percentage_12 DECIMAL(5,2) NOT NULL,
    year_12 VARCHAR(4) NOT NULL,
    neet_scores JSON,
    other_exam_name VARCHAR(100),
    other_exam_details TEXT,
    preferred_country VARCHAR(100) NOT NULL,
    preferred_university VARCHAR(255) NOT NULL,
    upload_documents VARCHAR(10) DEFAULT 'No',
    document_marksheet_10 VARCHAR(255),
    document_marksheet_12 VARCHAR(255),
    document_neet_scorecard VARCHAR(255),
    document_aadhar_front VARCHAR(255),
    document_aadhar_back VARCHAR(255),
    document_photograph VARCHAR(255),
    document_passport_front VARCHAR(255),
    document_passport_back VARCHAR(255),
    course VARCHAR(50) NOT NULL DEFAULT 'MBBS',
    source VARCHAR(100) NOT NULL DEFAULT 'MBBS Application Form',
    status ENUM('Pending', 'Under Review', 'Approved', 'Rejected', 'Documents Required') DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_student_apps_email (email),
    INDEX idx_student_apps_mobile (mobile),
    INDEX idx_student_apps_status (status),
    INDEX idx_student_apps_course (course),
    INDEX idx_student_apps_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: other_courses_applications
CREATE TABLE other_courses_applications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_middle_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(20) NOT NULL,
    nationality VARCHAR(50) NOT NULL,
    aadhar VARCHAR(12) NOT NULL,
    passport_status VARCHAR(50) NOT NULL,
    passport_number VARCHAR(50),
    file_number VARCHAR(50),
    passport_issue_date DATE,
    passport_expiry_date DATE,
    father_title VARCHAR(10),
    father_name VARCHAR(100) NOT NULL,
    father_occupation VARCHAR(100) NOT NULL,
    mother_title VARCHAR(10),
    mother_name VARCHAR(100) NOT NULL,
    mother_occupation VARCHAR(100),
    school_10_name VARCHAR(200) NOT NULL,
    board_10 VARCHAR(100) NOT NULL,
    percentage_10 DECIMAL(5,2) NOT NULL,
    year_10 INT NOT NULL,
    school_11_name VARCHAR(200),
    board_11 VARCHAR(100),
    percentage_11 DECIMAL(5,2),
    year_11 INT,
    school_12_status VARCHAR(50) NOT NULL,
    school_12_name VARCHAR(200),
    board_12 VARCHAR(100),
    percentage_12 DECIMAL(5,2),
    year_12 INT,
    ug_status VARCHAR(50),
    ug_degree VARCHAR(100),
    ug_college VARCHAR(255),
    ug_percentage DECIMAL(5,2),
    ug_year INT,
    pg_status VARCHAR(50),
    pg_degree VARCHAR(100),
    pg_college VARCHAR(255),
    pg_percentage DECIMAL(5,2),
    pg_year INT,
    any_other_course VARCHAR(10) DEFAULT 'No',
    other_course_name VARCHAR(100),
    other_course_college VARCHAR(255),
    other_course_percentage DECIMAL(5,2),
    other_course_year INT,
    gap_between_education VARCHAR(10) DEFAULT 'No',
    total_gap_years INT,
    gap_reason TEXT,
    english_exam VARCHAR(10) DEFAULT 'No',
    english_exam_year INT,
    english_exam_type VARCHAR(50),
    entrance_exam VARCHAR(10) DEFAULT 'No',
    entrance_exams TEXT,
    degree_name VARCHAR(200),
    branch_stream VARCHAR(200),
    preferred_countries VARCHAR(300),
    max_budget VARCHAR(100),
    work_experience VARCHAR(10) DEFAULT 'No',
    work_duration VARCHAR(50),
    visa_applied_prior VARCHAR(10) DEFAULT 'No',
    visa_country_name VARCHAR(100),
    visa_how_many_times INT,
    previous_visa_refusal VARCHAR(10) DEFAULT 'No',
    refusal_reason TEXT,
    refusal_country_name VARCHAR(100),
    comments TEXT,
    mobile VARCHAR(15) NOT NULL,
    whatsapp VARCHAR(15),
    email VARCHAR(100) NOT NULL,
    father_mobile VARCHAR(15) NOT NULL,
    mother_mobile VARCHAR(15),
    address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    pincode VARCHAR(10) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    upload_documents VARCHAR(100) DEFAULT 'No, Already share on WhatsApp or Email',
    course VARCHAR(50) DEFAULT 'Other Courses',
    source VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    document_marksheet_10 VARCHAR(255),
    document_marksheet_12 VARCHAR(255),
    document_ug_degree VARCHAR(255),
    document_pg_degree VARCHAR(255),
    document_aadhar_card VARCHAR(255),
    document_passport_front VARCHAR(255),
    document_passport_back VARCHAR(255),
    document_photograph VARCHAR(255),
    document_english_exam_cert VARCHAR(255),
    document_entrance_exam_scorecard VARCHAR(255),
    document_work_exp_certificate VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default admin user (password: admin123)
INSERT INTO users (name, email, password, role, phone, department, status, permissions)
VALUES
('Super Admin', 'admin@pulseeducation.com', '$2b$10$0t4LV5qLIj6izeIoDg8rc.3D9ruy108.HkIfvxkvWQwantPnsNn4G', 'Super Admin', '+919999999999', 'Management', 'active', '["all"]'),
('Telecaller 1', 'telecaller@pulseeducation.com', '$2b$10$3XlRO/N7fTP3gSr.iqYUg.WoW.HtVaSKUfjuxJuXo4pIoTICcAHNy', 'Telecaller', '+919888888888', 'Sales', 'active', '["view_assigned_leads", "add_call_logs", "update_lead_status"]');

-- Insert default company settings
INSERT INTO company_settings (id, companyName, email, phone, address, website, timezone, currency)
VALUES (1, 'Pulse Education', 'contact@pulseeducation.com', '+91 XXXXXXXXXX', 'India', 'www.pulseeducation.com', 'Asia/Kolkata', 'INR');

-- Schema creation complete
